image: 'gitpod/workspace-full'

tasks:
  - name: 'programming-challenges'
    before: 'npm install --global npm@7 && npm clean-install'
    init: 'npm run build && npm install --global'
    command: 'programming-challenges'
