image: 'gitpod/workspace-full'

tasks:
  - name: 'programming-challenges'
    before: 'npm install'
    init: 'npm run build'
    command: 'npm install --global && programming-challenges'

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: true
